# This is a basic workflow to help you get started with Actions

name: NETPKTCE

# Controls when the workflow will run
on:
  push:
    branches:
      - stable

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ${{github.workspace}}
          fetch-depth: 0
      
      # Runs a single command using the runners shell
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: '.'
          doxyfile-path: '.doxyfile'

      - name: Upload Website Documentation
        if: github.ref == 'refs/heads/stable'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{github.workspace}}
          CLEAN: true
